fmcg_analytics:
  target: local
  outputs:
    local:
      type: duckdb
      path: ../data/warehouse/fmcg.duckdb
      schema: analytics
      threads: 4
    bigquery:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT_ID', 'REPLACE_ME') }}"
      dataset: fmcg_analytics
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', 'REPLACE_ME') }}"
      location: "EU"
      threads: 4

