import {useEffect,useMemo,useReducer,useState} from "react";
import {api} from "./api";
import Chart from "./Chart";
import {appendFilters,emptyFilters,filterReducer,filtersFromSearch,filtersToSearch,type Filters} from "./filters";
type Summary={date_from:string|null,date_to:string|null,units:number,revenue:number,average_selling_price:number,active_stores:number,active_skus:number,freshness_note:string};
type Point={date:string,units:number,revenue:number}; type Breakdown={key:string,units:number,revenue:number};
type Profile={profile_id:string,display_name:string,disclaimer:string}; type Model={name:string,version:string,task:string,ready:boolean,prediction_horizon:string,target:string,limitation:string};
type Capability={capability:string,status:string}; type Artifact={name:string,status:string,caveat:string,total:number,items:Record<string,unknown>[]};
type Metadata={date_from:string,date_to:string,regions:(string|number)[],channels:string[],stores:(string|number)[],categories:string[],brands:string[],skus:(string|number)[],promotions:boolean[],semantics:string};
const pages=["Home","Sales Overview","Brand / Product","Store / Outlet","Forecast","Stockout Risk","Segments","Anomaly Review","Basket Insights","Promotions","Model Catalog"];
const artifactFor:Record<string,string>={Segments:"segments","Anomaly Review":"anomalies","Basket Insights":"basket-rules",Promotions:"promotions"};
const filteredPages=new Set(["Home","Sales Overview","Brand / Product","Store / Outlet"]);
export default function DashboardApp(){
 const initial=filtersFromSearch(location.search),[filters,dispatch]=useReducer(filterReducer,initial),[page,setPage]=useState("Home"),[metadata,setMetadata]=useState<Metadata|null>(null),[summary,setSummary]=useState<Summary|null>(null),[series,setSeries]=useState<Point[]>([]),[profile,setProfile]=useState<Profile|null>(null),[models,setModels]=useState<Model[]>([]),[capabilities,setCapabilities]=useState<Capability[]>([]),[breakdown,setBreakdown]=useState<Breakdown[]>([]),[artifact,setArtifact]=useState<Artifact|null>(null),[error,setError]=useState("");
 useEffect(()=>history.replaceState(null,"",`${location.pathname}${filtersToSearch(filters)}`),[filters]);
 useEffect(()=>{Promise.all([api<{items:Profile[],active:string}>("/api/v1/domain-packs"),api<{items:Model[]}>("/api/v1/models"),api<{items:Capability[]}>("/api/v1/capabilities"),api<Metadata>("/api/v1/analytics/filters")]).then(([p,m,c,f])=>{setProfile(p.items.find(x=>x.profile_id===p.active)??p.items[0]);setModels(m.items);setCapabilities(c.items);setMetadata(f)}).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!filteredPages.has(page))return;setError("");Promise.all([api<Summary>(appendFilters("/api/v1/bi/summary",filters)),api<{items:Point[]}>(appendFilters("/api/v1/bi/timeseries",filters))]).then(([s,t])=>{setSummary(s);setSeries(t.items)}).catch(e=>setError(String(e)))},[filters,page]);
 useEffect(()=>{setArtifact(null);setBreakdown([]);const dim=page==="Brand / Product"?"brand":page==="Store / Outlet"?"store":"";if(dim)api<{items:Breakdown[]}>(appendFilters(`/api/v1/bi/breakdown/${dim}`,filters)).then(x=>setBreakdown(x.items)).catch(e=>setError(String(e)));const name=artifactFor[page];if(name)api<Artifact>(`/api/v1/analytics/${name}?limit=50`).then(setArtifact).catch(e=>setError(String(e)))},[page,filters]);
 const active=Object.values(filters).reduce((n,x)=>n+(Array.isArray(x)?x.length:Number(Boolean(x))),0), trend=useMemo(()=>({tooltip:{trigger:"axis"},legend:{data:["Revenue","Units"]},xAxis:{type:"category",data:series.map(x=>x.date)},yAxis:[{type:"value",name:"Revenue"},{type:"value",name:"Units"}],series:[{name:"Revenue",type:"line",data:series.map(x=>x.revenue)},{name:"Units",type:"bar",yAxisIndex:1,data:series.map(x=>x.units)}]}),[series]),bars=useMemo(()=>({tooltip:{trigger:"axis"},xAxis:{type:"category",data:breakdown.map(x=>x.key),axisLabel:{rotate:35}},yAxis:{type:"value"},series:[{name:"Revenue",type:"bar",data:breakdown.map(x=>x.revenue)}]}),[breakdown]);
 return <div className="shell"><aside><h1>Sales Intelligence</h1><p>{profile?.display_name??"Loading profile"}</p>{pages.map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)} key={x}>{x}</button>)}<a href="http://localhost:5000" target="_blank" rel="noreferrer">MLflow UI</a></aside><main><header><div><small>ACTIVE PROFILE</small><h2>{page}</h2></div><span className="pill">Local V1.1</span></header><FilterBar filters={filters} metadata={metadata} active={active} dispatch={dispatch}/>{!filteredPages.has(page)&&active>0&&<p className="notice">Global sales filters are not applicable to this frozen artifact/model metadata view.</p>}{error&&<section className="error">{error}</section>}{filteredPages.has(page)&&!error&&!summary&&<section>Loading validated backend data…</section>}{summary&&<Page page={page} summary={summary} trend={trend} bars={bars} profile={profile} models={models} capabilities={capabilities} artifact={artifact}/>}<footer>{profile?.disclaimer} Data freshness: {summary?.date_to??"unavailable"}. Model versions are shown in the catalog.</footer></main></div>;
}
function FilterBar({filters,metadata,active,dispatch}:{filters:Filters,metadata:Metadata|null,active:number,dispatch:React.Dispatch<any>}){const select=(key:keyof Filters,label:string,values:(string|number)[])=><label>{label}<select value={(filters[key] as string[])[0]??""} onChange={e=>dispatch({type:"set",key,value:e.target.value?[e.target.value]:[]})}><option value="">All</option>{values.map(v=><option key={String(v)}>{String(v)}</option>)}</select></label>;return <section className="filters"><div className="filter-head"><strong>Global sales filters</strong><span>{active} active</span><button onClick={()=>dispatch({type:"clear"})}>Clear all</button></div><div className="filter-grid"><label>From<input type="date" min={metadata?.date_from} max={metadata?.date_to} value={filters.date_from} onChange={e=>dispatch({type:"set",key:"date_from",value:e.target.value})}/></label><label>To<input type="date" min={metadata?.date_from} max={metadata?.date_to} value={filters.date_to} onChange={e=>dispatch({type:"set",key:"date_to",value:e.target.value})}/></label>{select("regions","Region",metadata?.regions??[])}{select("channels","Channel",metadata?.channels??[])}{select("stores","Store",metadata?.stores??[])}{select("categories","Category",metadata?.categories??[])}{select("brands","Brand",metadata?.brands??[])}{select("skus","SKU",metadata?.skus??[])}<label>Promotion<select value={filters.promotion} onChange={e=>dispatch({type:"set",key:"promotion",value:e.target.value})}><option value="">All</option><option value="true">Promoted</option><option value="false">Not promoted</option></select></label></div><small>{metadata?.semantics??"Loading filter bounds…"}</small></section>}
function Page({page,summary,trend,bars,profile,models,capabilities,artifact}:{page:string,summary:Summary,trend:any,bars:any,profile:Profile|null,models:Model[],capabilities:Capability[],artifact:Artifact|null}){if(page==="Home")return <><section className="cards"><Card label="Profile" value={profile?.display_name??"—"}/><Card label="Capabilities" value={`${capabilities.filter(x=>x.status==="AVAILABLE").length} available`}/><Card label="Data through" value={summary.date_to??"No data"}/></section><section className="panel"><DataTable rows={capabilities}/></section></>;if(page==="Sales Overview")return <><Kpis s={summary}/><section className="panel"><h3>Sales over time</h3>{seriesEmpty(trend)?<p>No data for selected filters.</p>:<Chart option={trend}/>}<p>{summary.freshness_note}</p></section></>;if(page==="Brand / Product"||page==="Store / Outlet")return <><Kpis s={summary}/><section className="panel"><h3>Revenue contribution</h3>{seriesEmpty(bars)?<p>No data for selected filters.</p>:<Chart option={bars}/>}<p>Descriptive historical contribution; revenue is not profit.</p></section></>;if(page==="Forecast"||page==="Stockout Risk"){const task=page==="Forecast"?"forecasting":"stockout_classification",model=models.find(x=>x.task===task);return <section className="panel"><h3>Frozen serving model</h3><DataTable rows={model?[model]:[]}/><p>{model?.limitation}</p></section>}if(page==="Model Catalog")return <section className="panel"><DataTable rows={models}/><p>DVC owns artifacts; MLflow owns run and registry metadata.</p></section>;return <section className="panel"><h3>{page}</h3>{artifact?<><p>{artifact.caveat}. Rows: {artifact.total}.</p><DataTable rows={artifact.items}/></>:<p>Loading versioned analytical artifact…</p>}<Caveat page={page}/></section>}
function seriesEmpty(o:any){return !o.series?.some((s:any)=>s.data?.length)} function Kpis({s}:{s:Summary}){return <section className="cards"><Card label="Revenue" value={s.revenue.toLocaleString()}/><Card label="Units sold" value={s.units.toLocaleString()}/><Card label="Avg selling price" value={s.average_selling_price.toFixed(2)}/><Card label="Stores / SKUs" value={`${s.active_stores} / ${s.active_skus}`}/></section>} function Card({label,value}:{label:string,value:string}){return <article><small>{label}</small><strong>{value}</strong></article>} function DataTable({rows}:{rows:object[]}){if(!rows.length)return <p>No supported rows available.</p>;const columns=Object.keys(rows[0]).slice(0,8);return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,50).map((r,i)=>{const values=r as Record<string,unknown>;return <tr key={i}>{columns.map(c=><td key={c}>{String(values[c]??"—")}</td>)}</tr>})}</tbody></table></div>} function Caveat({page}:{page:string}){const notes:Record<string,string>={Segments:"Exploratory profiles; temporal retention is limited and assignment remains blocked.","Anomaly Review":"Candidates are unreviewed, not confirmed anomalies.","Basket Insights":"Association is neither causation nor recommendation.",Promotions:"PRE/DURING/POST comparisons are descriptive, not causal ROI."};return <p className="caveat">{notes[page]}</p>}
